### ISSUE TITLE
Add a way to empty the cs_toastQueue.

### ISSUE THREAD

**Issue by chrispolson-si** [scalessec/Toast#100]
I'm using the toast library to display chat messages when the user is not on the chat screen. So if there are 5 messages, "A", "B", "C", "D", "E" all queued up... A will show for 2 seconds... then B will show for 2 seconds etc.

However, if the user now decides to open the full chat window... they will continue to get "C", "D", and "E"... but at this point it is unwanted because the user can see all the message in the full chat window of the app.

There needs to be a way to clear all currently queued toasts.

**Comment by scalessec** [comment]
Added in `4.0.0`. Currently on master.
