### ISSUE TITLE
Keyboard closes automatically

### ISSUE THREAD

**Issue by jithin** [scalessec/Toast#104]
The keyboard closes automatically if the keyboard is shown over a toast message.
Steps to reproduce:

1. Call showToast()
2. Click on a UITextField to show keyboard. Keyboard covers the toast message.
3. When toast hides, the keyboard also get dismissed.

The issue goes away when I comment out the line` [toast removeFromSuperview];` inside, `- (void)cs_hideToast:(UIView *)toast fromTap:(BOOL)fromTap`.

**Comment by scalessec** [comment]
I'm unable to reproduce.
