### ISSUE TITLE
Restrain the width of toast

### ISSUE THREAD

**Issue by quazarteam** [scalessec/Toast#108]
Hello!

Thanks for this excellent component. The only question is how can i make toast with certain width, or restrain it to not be more than XXX pixels?

right now, it seems to take as much width as it is possible.

**Comment by scalessec** [comment]
Please don't open issues for these types of questions. You can't set an explicit width, but you can use `maxWidthPercentage` in `CSToastStyle` to set the maximum width percentage relative to the Toast's superview.
