### ISSUE TITLE
is it possible to show it on top of the keyboard or just above?

### ISSUE THREAD

**Issue by marconealberto** [scalessec/Toast#111]
If the keyboard is open, the toast is not visible when the position is at the bottom

**Comment by scalessec** [comment]
You can position the toast wherever you want.

**Comment by marconealberto** [comment]
I meant ON TOP of the keyboard.. right now the toast is hidden behind the keyboard if it's shown at the bottom of the screen.

**Comment by scalessec** [comment]
The keyboard is a subview of the window, so if you present the toast in the window it’ll appear on top.
