### ISSUE TITLE
键盘会挡住

### ISSUE THREAD

**Issue by hygtjm** [scalessec/Toast#128]
键盘没有收起的时候 会被键盘挡住 有什么解决方法么

**Comment by scalessec** [comment]
#111. Present the toast in the window if you want it to be displayed on top of the keyboard. Alternatively you can specify a position for the toast that wouldn't be blocked by the keyboard.

**Comment by hygtjm** [comment]
显示是在 屏幕底部 我是加在window上的 还是会被键盘挡住
