### ISSUE TITLE
Could not find module 'Toast_Swift' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios

### ISSUE THREAD

**Issue by MingYik** [scalessec/Toast#129]
ios 13 , xcode 11.1 , iphone 6ps
Could not find module 'Toast_Swift' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios

**Comment by UzumakiAlfredo** [comment]
This fixed my problem:
In build settings select YES on "Always embed swift standard libraries"
