### ISSUE TITLE
Privacy manifest required by Apple

### ISSUE THREAD

**Issue by wenfeng-duan** [scalessec/Toast#140]
Hi team,

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file.
Apple has explicitly mentioned Reachability as one of the third party SDKs that must include a privacy manifest otherwise any App that includes it is not allowed to release an update (or new app) to the store.

Does this SDK need a privacy manifest? If yes, is there any plans to add a privacy manifest?

https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Duan

**Comment by scalessec** [comment]
https://github.com/scalessec/Toast?tab=readme-ov-file#privacy
