### ISSUE TITLE
Toast.podspec

### ISSUE THREAD

**Issue by glary** [scalessec/Toast#141]
s.resource_bundles = {'Toast' => ['Resources/PrivacyInfo.xcprivacy']}

**Comment by dioi2000** [comment]
@scalessec check this requset please

**Comment by ceebows** [comment]
you can refer to this issue for some clarification on why this is needed.
https://github.com/vonovak/react-native-simple-toast/issues/79

**Comment by scalessec** [comment]
Fixed with #144
