### ISSUE TITLE
Multiple toasts get overlaid on top of each other

### ISSUE THREAD

**Issue by simonbromberg** [scalessec/Toast#24]
Tried calling hideToastActivity but doesn't seem to find the toast view
EDIT: realize that's for the spinner. Doesn't seem to be a method for hiding the toast manually before loading another one, plus seems to make sense to hide any that are still visible automatically.

Example:
![ios simulator screen shot feb 16 2014 5 43 52 pm](https://f.cloud.github.com/assets/2942298/2181629/e8a68cac-975b-11e3-94cf-83ae97877bfd.png)

**Comment by scalessec** [comment]
Toast 3.0 supports queueing of toast views, and it's enabled by default.

**Comment by Farteen** [comment]
Thank you~~
