### ISSUE TITLE
Add support for customizable defaults (eg. make view alpha configurable)

### ISSUE THREAD

**Issue by cjwirth** [scalessec/Toast#28]
The way the code is currently written, if you show a toast, it will always be completely opaque -- the alpha is always 1.

Originally, I thought passing in the alpha value might be a good way to do it, but there are some other values that might be nice to configure (basically, many of the `static const` values). It might be nice to add support to customize these values.

I thought of a few ways this could be done. The easiest might be to read from UserDefaults to see if there is a value to use instead of the hardcoded value. If not, it uses the original value.

**Comment by scalessec** [comment]
Custom styling is officially supported in Toast 3.0.
