### ISSUE TITLE
Add NSTimer to main run loop.

### ISSUE THREAD

**Issue by euroboy** [scalessec/Toast#46]
Not a bug, just an improvement:
NSTimer *timer = [NSTimer scheduledTimerWithTimeInterval:duration target:self selector:@selector(toastTimerDidFinish:) userInfo:toast repeats:NO];
[[NSRunLoop mainRunLoop] addTimer:timer forMode:NSRunLoopCommonModes];

**Comment by scalessec** [comment]
Added to Toast 3.0.
