### ISSUE TITLE
how to change background view's alpha

### ISSUE THREAD

**Issue by hengchengfei** [scalessec/Toast#48]
When use [self.view makeToastActivity],
how to set the background view's alpha,not the activityView's alpha.

thank you!

**Comment by scalessec** [comment]
Updating line 24 in `UIView+Toast.m` to a value of your liking should do the trick:
`static const CGFloat CSToastOpacity             = 0.8;`

**Comment by hengchengfei** [comment]
@scalessec  appreciate for your help

**Comment by scalessec** [comment]
Instead of this hack, it would be best to use the styling options introduced in Toast 3.0.
