### ISSUE TITLE
Toast should extend UIWindow

### ISSUE THREAD

**Issue by kashzonal** [scalessec/Toast#63]
Displaying a toast in a view which has scrollview cannot guarantee that it would appear where you expect it to be. Using the window's frame guarantees that positions will constant.

**Comment by scalessec** [comment]
You're already free to do this if you wish because UIWindow is a subclass of UIView. Generally though it's bad practice to add a view directly to the window. In most cases you should just display the Toast in one of the scrollview's superviews.
