### ISSUE TITLE
Toast disappears behind Tab Bar

### ISSUE THREAD

**Issue by greuff** [scalessec/Toast#74]
The default toast (bottom) is hidden behind the tab bar when calling it from a TableViewController inside a NavigationController inside a TabBarController (other configurations not tested).

**Comment by scalessec** [comment]
What view are you presenting the toast view in? If you want it to be on top of the tab bar you need to present it in the tab bar controller's view.

For example:
`[self.tabBarController.view makeToast:@"Hello World"];`

Your other option is to wrap a `CGPoint` in an `NSValue` object and specify a position above the tab bar (you can see an example in the demo project). You might need to do this anyway, as I suspect the toast will be positioned on top of the tab bar buttons and that may not be ideal either.

**Comment by greuff** [comment]
Thank you, that worked!
