### ISSUE TITLE
EXC_BAD_ACCESS on ios 7 for [[CSToastStyle alloc] initWithDefaultStyle]

### ISSUE THREAD

**Issue by enwar3** [scalessec/Toast#82]
Hi! Seeing EXC_BAD_ACCESS for all ios 7 devices when `[[CSToastStyle alloc] initWithDefaultStyle]` is called. Thousands of crashes (can provide crashlytics but reports if it helps).

Any ideas?

**Comment by scalessec** [comment]
Hmm, seems weird that it would crash there. Any other info you can provide about the stack track or how you're using the library? I no longer have a device with iOS7 and XCode 7.3 no longer has iOS7 simulators.

**Comment by enwar3** [comment]
Thanks for the quick response! Yea I also don't have an iOS7 device and realized the simulator doesn't work :(

Here are the crash reports: http://crashes.to/s/998d433f735

Here's the code snippet - we're using it in a pretty standard way from a view controller:
```
    // Get the default style and align the toast
    CSToastStyle *style = [self getToastStyle];
    style.titleAlignment = NSTextAlignmentCenter;
    style.messageAlignment = NSTextAlignmentCenter;
    
    // Show the toast
    [self.view makeToast:@"Only notify nearby friends!" duration:MESSAGE_TIME position:CSToastPositionCenter title:@"Location enabled! 🙌" image:nil style:style completion:nil];
```

**Comment by scalessec** [comment]
Bumping the minimum target to iOS8 to support Carthage. Closing this.
