### ISSUE TITLE
Need  hide/clear Toast functions

### ISSUE THREAD

**Issue by mqeizi** [scalessec/Toast#83]
When back to last ViewContoller , a toast view  will still be shown in duration. So need hide  or remove  toast maked before .

**Comment by Sollex-21412** [comment]
+1

**Comment by smidaharoun** [comment]
+1

**Comment by scalessec** [comment]
Currently on `master`. Sorry for the delay. I'll cut a new version for CocoaPods after I do a bit more testing. Feedback welcome.
