### ISSUE TITLE
Using Toast in a project with both Objective-C and Swift

### ISSUE THREAD

**Issue by timgcarlson** [scalessec/Toast#86]
In a project with both Objective-C and Swift, what is the best way to use Toast? Making a Toast will happen in both Objective-C and Swift. I've tried using the Objective-C version in Swift and vice versa. I've also tried adding both the framework.

So how can I use Toast in an Objective-C class and Swift class living in the same project?

**Comment by scalessec** [comment]
Objective-C libraries can be used with Swift, but not vice versa. Your best bet would be to use the Objective-C version and then just add `UIView+Toast.h` to your bridging header to expose it to Swift classes. Did that not work for you?

**Comment by timgcarlson** [comment]
@scalessec Thanks for the quick response! That was the first thing I thought to try, but my bridging header can't find that file (_UIView+Toast.h file not found_). I have never included a Pod in the bridging header, so perhaps I'm doing something wrong here?

The curious thing is that when I add both Objective-C and Swift libraries (via CocoaPods) I get no runtime errors in either Objective-C or Swift classes. Then when I run it, the Obj-C version works, but the Swift version crashes because it calls the Objective-C code which uses `CSToastStyle` and I passed `ToastStyle`. Furthermore with this same setup, I can call `makeToast` from a Swift class with only the string parameter and it will successfully display the toast using the Objective-C version of the library. So my problem also seems to be around using `CSToastStyle` in a Swift class.

So somehow when both libraries are in the project, the Swift class can find the Objective-C category and uses that one over the Swift extension.

Hope this is clear, let me know if you need any clarifications.

**Comment by timgcarlson** [comment]
Alright, got this to work, sorry for the long-winded explanation before. What needed to be done was the following...

1. Use the Objective-C version with CocoaPods.
2. Use the `use_frameworks!` keyword in the Podfile (was already doing this). This includes the library as a dependency and packages it as a framework.
3. Import the packaged framework as in the Swift file where it's used with `import Toast`.

I suppose if this were installed manually (without CocoaPods) then you would just import `UIView+Toast.h' in the bridging header.

BTW, thanks for this awesome library!

**Comment by scalessec** [comment]
Great. If there's anything you think should be added to the README to clarify this use case just send a PR and I'll merge it. I gave up using CocoaPods years ago (far too much time lost diagnosing issues just like this), so I'm usually not aware when issues pop up.
