### ISSUE TITLE
Toast hides behind the Tabbar Controller

### ISSUE THREAD

**Issue by shahdhiren** [scalessec/Toast#89]
By default showing the Toast in bottom on Tabbar controller screen is getting hidden behind the Tabs. I am using the UIView category of showing the Toast message. i.e. `self.view.makeToast()` method.

Is there any way to change this behaviour? What would be the quickest solution?

**Comment by scalessec** [comment]
Please look at the closed issues before opening a new ticket. You'll find your answer in #74.
